const bats = [
    // --- ORIGINAL 25 BATS (Updated with missing form properties) ---
    {
        batName: "Salix Pod",
        brand: "Salix",
        budget: 450,
        handleShape: "Oval",
        weightPreference: "Light",
        battingStyle: "Front Foot",
        playingLevel: "Professional",
        battingApproach: "Vertical Bat",
        strength: "Timing",
        battingWeakness: "Short Ball",
        weight: 1180,
        description: "Large middle, ideal for elegant stroke makers."
    },
    {
        batName: "Salix AJK",
        brand: "Salix",
        budget: 375,
        handleShape: "Semi Oval",
        weightPreference: "Medium",
        battingStyle: "Balanced",
        playingLevel: "Club",
        battingApproach: "Vertical Bat",
        strength: "Shot Placement",
        battingWeakness: "Swing",
        weight: 1170,
        description: "Excellent control and balance."
    },
    {
        batName: "GM Diamond",
        brand: "GM",
        budget: 400,
        handleShape: "Round",
        weightPreference: "Medium",
        battingStyle: "Front Foot",
        playingLevel: "Professional",
        battingApproach: "Vertical Bat",
        strength: "Timing",
        battingWeakness: "Yorkers",
        weight: 1160,
        description: "Favoured by top-order batsmen. Designed with Ben Stokes."
    },
    {
        batName: "GM Mana",
        brand: "GM",
        budget: 325,
        handleShape: "Semi Oval",
        weightPreference: "Light",
        battingStyle: "Balanced",
        playingLevel: "Club",
        battingApproach: "Balanced",
        strength: "Footwork",
        battingWeakness: "Spin",
        weight: 1170,
        description: "Versatile bat for all conditions with a great pick-up."
    },
    {
        batName: "GM Noir",
        brand: "GM",
        budget: 375,
        handleShape: "Round",
        weightPreference: "Heavy",
        battingStyle: "Back Foot",
        playingLevel: "Professional",
        battingApproach: "Horizontal Bat",
        strength: "Power Hitting",
        battingWeakness: "Spin",
        weight: 1190,
        description: "Powerful profile for aggressive strokeplay."
    },
    {
        batName: "Gray Nicolls Legend",
        brand: "Gray Nicolls",
        budget: 500,
        handleShape: "Semi Oval",
        weightPreference: "Medium",
        battingStyle: "Front Foot",
        playingLevel: "Professional",
        battingApproach: "Vertical Bat",
        strength: "Timing",
        battingWeakness: "Swing",
        weight: 1175,
        description: "Premium bat with huge sweet spot and iconic branding."
    },
    {
        batName: "Gray Nicolls Nova",
        brand: "Gray Nicolls",
        budget: 300,
        handleShape: "Oval",
        weightPreference: "Light",
        battingStyle: "Balanced",
        playingLevel: "Club",
        battingApproach: "Balanced",
        strength: "Shot Placement",
        battingWeakness: "Short Ball",
        weight: 1165,
        description: "Light pickup and great balance for touch players."
    },
    {
        batName: "Gray Nicolls Powerbow",
        brand: "Gray Nicolls",
        budget: 425,
        handleShape: "Round",
        weightPreference: "Heavy",
        battingStyle: "Front Foot",
        playingLevel: "Professional",
        battingApproach: "Vertical Bat",
        strength: "Power Hitting",
        battingWeakness: "Spin",
        weight: 1190,
        description: "Massive edges and powerful low hitting zone."
    },
    {
        batName: "Chase FLC",
        brand: "Chase",
        budget: 350,
        handleShape: "Semi Oval",
        weightPreference: "Medium",
        battingStyle: "Balanced",
        playingLevel: "Club",
        battingApproach: "Balanced",
        strength: "Timing",
        battingWeakness: "Footwork",
        weight: 1170,
        description: "Excellent all-round performance, handcrafted in Hampshire."
    },
    {
        batName: "Chase R11",
        brand: "Chase",
        budget: 475,
        handleShape: "Oval",
        weightPreference: "Medium",
        battingStyle: "Front Foot",
        playingLevel: "Professional",
        battingApproach: "Vertical Bat",
        strength: "Shot Placement",
        battingWeakness: "Swing",
        weight: 1180,
        description: "Premium handcrafted English willow with thick edges."
    },
    {
        batName: "Newbery Excalibur",
        brand: "Newbery",
        budget: 325,
        handleShape: "Round",
        weightPreference: "Light",
        battingStyle: "Balanced",
        playingLevel: "Club",
        battingApproach: "Balanced",
        strength: "Footwork",
        battingWeakness: "Yorkers",
        weight: 1170,
        description: "Traditional profile with excellent pickup."
    },
    {
        batName: "Newbery Infinity",
        brand: "Newbery",
        budget: 375,
        handleShape: "Semi Oval",
        weightPreference: "Medium",
        battingStyle: "Front Foot",
        playingLevel: "Professional",
        battingApproach: "Vertical Bat",
        strength: "Timing",
        battingWeakness: "Swing",
        weight: 1180,
        description: "Built for long innings and sheer elegance."
    },
    {
        batName: "B3 Beluga",
        brand: "B3",
        budget: 425,
        handleShape: "Round",
        weightPreference: "Heavy",
        battingStyle: "Front Foot",
        playingLevel: "Professional",
        battingApproach: "Vertical Bat",
        strength: "Power Hitting",
        battingWeakness: "Spin",
        weight: 1190,
        description: "Massive profile for aggressive batsmen. Custom made in Nottingham."
    },
    {
        batName: "B3 Hammer",
        brand: "B3",
        budget: 325,
        handleShape: "Semi Oval",
        weightPreference: "Heavy",
        battingStyle: "Back Foot",
        playingLevel: "Club",
        battingApproach: "Horizontal Bat",
        strength: "Power Hitting",
        battingWeakness: "Footwork",
        weight: 1200,
        description: "Suited for pull and cut shots."
    },
    {
        batName: "Millichamp & Hall Players",
        brand: "Millichamp & Hall",
        budget: 600,
        handleShape: "Oval",
        weightPreference: "Medium",
        battingStyle: "Balanced",
        playingLevel: "Professional",
        battingApproach: "Balanced",
        strength: "Timing",
        battingWeakness: "Swing",
        weight: 1175,
        description: "Handcrafted premium English willow from Taunton."
    },
    {
        batName: "Viking Thor",
        brand: "Viking",
        budget: 275,
        handleShape: "Round",
        weightPreference: "Heavy",
        battingStyle: "Front Foot",
        playingLevel: "Club",
        battingApproach: "Vertical Bat",
        strength: "Power Hitting",
        battingWeakness: "Short Ball",
        weight: 1190,
        description: "Strong profile for attacking cricket."
    },
    {
        batName: "Viking Valhalla",
        brand: "Viking",
        budget: 325,
        handleShape: "Semi Oval",
        weightPreference: "Medium",
        battingStyle: "Balanced",
        playingLevel: "Club",
        battingApproach: "Balanced",
        strength: "Timing",
        battingWeakness: "Spin",
        weight: 1170,
        description: "Excellent all-round bat."
    },
    {
        batName: "H4L Original",
        brand: "H4L",
        budget: 350,
        handleShape: "Oval",
        weightPreference: "Light",
        battingStyle: "Balanced",
        playingLevel: "Professional",
        battingApproach: "Balanced",
        strength: "Shot Placement",
        battingWeakness: "Swing",
        weight: 1165,
        description: "Beautiful pickup and control."
    },
    {
        batName: "H4L Black Edition",
        brand: "H4L",
        budget: 450,
        handleShape: "Round",
        weightPreference: "Medium",
        battingStyle: "Front Foot",
        playingLevel: "Professional",
        battingApproach: "Vertical Bat",
        strength: "Timing",
        battingWeakness: "Yorkers",
        weight: 1180,
        description: "Premium performance bat."
    },
    {
        batName: "Warsop Platinum",
        brand: "Warsop",
        budget: 450,
        handleShape: "Semi Oval",
        weightPreference: "Heavy",
        battingStyle: "Front Foot",
        playingLevel: "Professional",
        battingApproach: "Vertical Bat",
        strength: "Power Hitting",
        battingWeakness: "Spin",
        weight: 1195,
        description: "Huge edges and big sweet spot. Essex heritage."
    },
    {
        batName: "Warsop Stealth",
        brand: "Warsop",
        budget: 325,
        handleShape: "Round",
        weightPreference: "Light",
        battingStyle: "Back Foot",
        playingLevel: "Club",
        battingApproach: "Horizontal Bat",
        strength: "Footwork",
        battingWeakness: "Short Ball",
        weight: 1170,
        description: "Ideal for modern strokeplay."
    },
    {
        batName: "Duncan Fearnley Magnum",
        brand: "Duncan Fearnley",
        budget: 325,
        handleShape: "Oval",
        weightPreference: "Medium",
        battingStyle: "Balanced",
        playingLevel: "Club",
        battingApproach: "Balanced",
        strength: "Defense",
        battingWeakness: "Footwork",
        weight: 1175,
        description: "Traditional English bat profile from Worcester."
    },
    {
        batName: "Duncan Fearnley JDB",
        brand: "Duncan Fearnley",
        budget: 400,
        handleShape: "Semi Oval",
        weightPreference: "Medium",
        battingStyle: "Front Foot",
        playingLevel: "Professional",
        battingApproach: "Vertical Bat",
        strength: "Timing",
        battingWeakness: "Swing",
        weight: 1180,
        description: "Excellent middle and pickup."
    },
    {
        batName: "Kippax Players Edition",
        brand: "Kippax",
        budget: 525,
        handleShape: "Semi Oval",
        weightPreference: "Medium",
        battingStyle: "Balanced",
        playingLevel: "Professional",
        battingApproach: "Balanced",
        strength: "Shot Placement",
        battingWeakness: "Swing",
        weight: 1170,
        description: "Premium handcrafted bat grown from their own willow trees."
    },
    {
        batName: "Kippax Classic",
        brand: "Kippax",
        budget: 350,
        handleShape: "Round",
        weightPreference: "Light",
        battingStyle: "Balanced",
        playingLevel: "Club",
        battingApproach: "Balanced",
        strength: "Defense",
        battingWeakness: "Yorkers",
        weight: 1165,
        description: "Traditional shape and feel."
    },

    // --- NEW 20 UK-BASED BATS ---
    {
        batName: "Keeley Superior",
        brand: "Keeley",
        budget: 610,
        handleShape: "Semi Oval",
        weightPreference: "Medium",
        battingStyle: "Front Foot",
        playingLevel: "Professional",
        battingApproach: "Vertical Bat",
        strength: "Timing",
        battingWeakness: "Swing",
        weight: 1180,
        description: "Master crafted in East Sussex by Tim Keeley. Full profile with no incurve."
    },
    {
        batName: "Keeley Worx",
        brand: "Keeley",
        budget: 280,
        handleShape: "Oval",
        weightPreference: "Light",
        battingStyle: "Balanced",
        playingLevel: "Club",
        battingApproach: "Balanced",
        strength: "Shot Placement",
        battingWeakness: "Spin",
        weight: 1160,
        description: "Exceptional value from elite batmakers. Superb lightweight pickup."
    },
    {
        batName: "Phantom Dark Edition LE",
        brand: "Phantom",
        budget: 540,
        handleShape: "Round",
        weightPreference: "Heavy",
        battingStyle: "Back Foot",
        playingLevel: "Professional",
        battingApproach: "Horizontal Bat",
        strength: "Power Hitting",
        battingWeakness: "Short Ball",
        weight: 1195,
        description: "Menacing dark aesthetics paired with explosive power."
    },
    {
        batName: "Phantom PS7",
        brand: "Phantom",
        budget: 250,
        handleShape: "Semi Oval",
        weightPreference: "Medium",
        battingStyle: "Balanced",
        playingLevel: "Club",
        battingApproach: "Balanced",
        strength: "Footwork",
        battingWeakness: "Spin",
        weight: 1175,
        description: "Versatile profile for the elegant all-round club cricketer."
    },
    {
        batName: "Woodstock Tour Classic",
        brand: "Woodstock",
        budget: 450,
        handleShape: "Semi Oval",
        weightPreference: "Medium",
        battingStyle: "Front Foot",
        playingLevel: "Professional",
        battingApproach: "Vertical Bat",
        strength: "Timing",
        battingWeakness: "Yorkers",
        weight: 1180,
        description: "Award-winning bat known for incredible ping and balance."
    },
    {
        batName: "Woodstock Platinum",
        brand: "Woodstock",
        budget: 350,
        handleShape: "Oval",
        weightPreference: "Light",
        battingStyle: "Balanced",
        playingLevel: "Club",
        battingApproach: "Balanced",
        strength: "Shot Placement",
        battingWeakness: "Swing",
        weight: 1165,
        description: "Sleek shaping allows for ultra-fast hand speed."
    },
    {
        batName: "Aldred Vetus",
        brand: "Aldred",
        budget: 400,
        handleShape: "Round",
        weightPreference: "Medium",
        battingStyle: "Balanced",
        playingLevel: "Professional",
        battingApproach: "Balanced",
        strength: "Timing",
        battingWeakness: "Spin",
        weight: 1175,
        description: "Bespoke Derbyshire craftsmanship with a mid-to-low swell."
    },
    {
        batName: "Aldred Signum",
        brand: "Aldred",
        budget: 300,
        handleShape: "Oval",
        weightPreference: "Light",
        battingStyle: "Front Foot",
        playingLevel: "Club",
        battingApproach: "Vertical Bat",
        strength: "Footwork",
        battingWeakness: "Short Ball",
        weight: 1160,
        description: "Traditional sweeping spine delivering maximum edge thickness."
    },
    {
        batName: "Hell4Leather Origin",
        brand: "Hell4Leather",
        budget: 280,
        handleShape: "Semi Oval",
        weightPreference: "Light",
        battingStyle: "Balanced",
        playingLevel: "Club",
        battingApproach: "Balanced",
        strength: "Shot Placement",
        battingWeakness: "Swing",
        weight: 1155,
        description: "High sweet-spot perfect for bouncy wickets and quick wrists."
    },
    {
        batName: "Hell4Leather Pro Spec",
        brand: "Hell4Leather",
        budget: 480,
        handleShape: "Round",
        weightPreference: "Heavy",
        battingStyle: "Back Foot",
        playingLevel: "Professional",
        battingApproach: "Horizontal Bat",
        strength: "Power Hitting",
        battingWeakness: "Short Ball",
        weight: 1200,
        description: "Designed for T20 dominance with an extended spine into the toe."
    },
    {
        batName: "Salix Raw",
        brand: "Salix",
        budget: 425,
        handleShape: "Semi Oval",
        weightPreference: "Medium",
        battingStyle: "Balanced",
        playingLevel: "Professional",
        battingApproach: "Balanced",
        strength: "Timing",
        battingWeakness: "Swing",
        weight: 1175,
        description: "Unpolished, natural finish showcasing immaculate willow grain."
    },
    {
        batName: "Salix SLX",
        brand: "Salix",
        budget: 350,
        handleShape: "Oval",
        weightPreference: "Light",
        battingStyle: "Front Foot",
        playingLevel: "Club",
        battingApproach: "Vertical Bat",
        strength: "Defense",
        battingWeakness: "Yorkers",
        weight: 1160,
        description: "Contemporary pressing for immediate performance out of the wrapper."
    },
    {
        batName: "Newbery Heritage",
        brand: "Newbery",
        budget: 500,
        handleShape: "Round",
        weightPreference: "Medium",
        battingStyle: "Balanced",
        playingLevel: "Professional",
        battingApproach: "Balanced",
        strength: "Timing",
        battingWeakness: "Spin",
        weight: 1180,
        description: "Classic Sussex profiling, reviving traditional English bat making."
    },
    {
        batName: "Newbery Phantom (Junior/Beginner)",
        brand: "Newbery",
        budget: 180,
        handleShape: "Semi Oval",
        weightPreference: "Light",
        battingStyle: "Front Foot",
        playingLevel: "Beginner",
        battingApproach: "Vertical Bat",
        strength: "Footwork",
        battingWeakness: "Swing",
        weight: 1140,
        description: "Highly forgiving blade for those developing their technique."
    },
    {
        batName: "Gray Nicolls Vapour",
        brand: "Gray Nicolls",
        budget: 350,
        handleShape: "Round",
        weightPreference: "Medium",
        battingStyle: "Front Foot",
        playingLevel: "Club",
        battingApproach: "Vertical Bat",
        strength: "Power Hitting",
        battingWeakness: "Yorkers",
        weight: 1180,
        description: "Mid-low swell designed for front foot domination."
    },
    {
        batName: "Gray Nicolls Shockwave",
        brand: "Gray Nicolls",
        budget: 300,
        handleShape: "Semi Oval",
        weightPreference: "Heavy",
        battingStyle: "Back Foot",
        playingLevel: "Club",
        battingApproach: "Horizontal Bat",
        strength: "Power Hitting",
        battingWeakness: "Spin",
        weight: 1195,
        description: "Pronounced high swell for aggressive cross-bat strokes."
    },
    {
        batName: "Millichamp & Hall Harlequin",
        brand: "Millichamp & Hall",
        budget: 450,
        handleShape: "Oval",
        weightPreference: "Light",
        battingStyle: "Balanced",
        playingLevel: "Professional",
        battingApproach: "Balanced",
        strength: "Shot Placement",
        battingWeakness: "Footwork",
        weight: 1165,
        description: "M&H's most popular profile. Concaved back for feathery pickup."
    },
    {
        batName: "Millichamp & Hall C100",
        brand: "Millichamp & Hall",
        budget: 380,
        handleShape: "Semi Oval",
        weightPreference: "Medium",
        battingStyle: "Front Foot",
        playingLevel: "Club",
        battingApproach: "Vertical Bat",
        strength: "Timing",
        battingWeakness: "Swing",
        weight: 1175,
        description: "Thick edges maintained low down the blade for sluggish English tracks."
    },
    {
        batName: "Gunn & Moore Chroma",
        brand: "GM",
        budget: 350,
        handleShape: "Round",
        weightPreference: "Medium",
        battingStyle: "Balanced",
        playingLevel: "Club",
        battingApproach: "Balanced",
        strength: "Footwork",
        battingWeakness: "Yorkers",
        weight: 1170,
        description: "Sweeping spine and traditional face profiling."
    },
    {
        batName: "Gunn & Moore Sparq",
        brand: "GM",
        budget: 280,
        handleShape: "Oval",
        weightPreference: "Light",
        battingStyle: "Back Foot",
        playingLevel: "Club",
        battingApproach: "Horizontal Bat",
        strength: "Shot Placement",
        battingWeakness: "Short Ball",
        weight: 1160,
        description: "Ultra-light pickup making it lethal for cuts and pulls."
    }
];
module.exports = bats;